language: go
os: linux

stages:
  - img-build
  - unit-test
  - deploy-registry
  - notification

services:
  - docker

branches:
  only:
    - master
    - development

before_script:
  - docker info
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin


jobs:
  include:
    - name: "Build Docker Image"
      stage: img-build
      script:
        - docker build -t $CI_REGISTRY_USER/kitana .
        - docker push $CI_REGISTRY_USER/kitana

    - name: "Unit Test Golang"
      stage: unit-test
      script:
        - go test -v        
    
    - name: "Notifying on Success"
      stage: notification
      after_success:
        - echo "funfou"

    - name: "Notifying on Failure"
      stage: notification
      after_failure:
        - echo "deu ruim"
