language: go
os: linux

stages:
  - img-build
  - unit-test
  - deploy-registry
  - notification

services:
  - docker

branches:
  only:
    - master
    - development

before_script:
  - docker info
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin


jobs:
  include:
    - stage: Build Docker Image
      name: img-build
      script:
        - docker build -t $CI_REGISTRY_USER/kitana .
        - docker image ls

jobs:
  include:
    - stage: Unit Test Golang
      name: unit-test
      script: go test -v

jobs:
  include:
    - stage: Deploy on Docker Hub
      name: deploy-registry
      script: docker push $CI_REGISTRY_USER/kitana

