language: go
os: linux

stages:
  - img-build
  - unit-test
  - deploy-registry
  - notification

services:
  - docker

branches:
  only:
    - master

before_script:
  - docker info
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
  - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG##*/}


jobs:
  include:
    - name: "Build Docker Image"
      stage: img-build
      script:
        - docker build -t $CI_REGISTRY_USERR/$TRAVIS_REPO_SLUG .
        - docker push $CI_REGISTRY_USER/$TRAVIS_REPO_SLUG

    - name: "Unit Test Golang"
      stage: unit-test
      script:
        - go test -v        
       
    - name: "Notifying on Success"
      after_success:
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL

    - name: "Notifying on Failure"
      after_failure:
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
